
// --- Define the tool (function) the AI can call ---
export const submitCodeTool = {
  name: "submitCode",
  description: "Submits the generated HTML, CSS, and JavaScript code for the user's component.",
  parameters: {
    type: "object",
    properties: {
      html: { type: "string", description: "The complete HTML code for the component's body. It should not include <html> or <body> tags." },
      css: { type: "string", description: "The complete CSS code to style the component." },
      js: { type: "string", description: "The complete JavaScript code to make the component interactive." }
    },
    required: ["html", "css", "js"]
  }
};

export const enhancePromptTool = {
  name: "enhancePrompt",
  description: "Submits an enhanced version of the user prompt in 20-30 words for better results.",
  parameters: {
    type: "object",
    properties: {
      prompt: { type: "string", description: "Enhanced prompt version generated by the LLM." }
    },
    required: ["prompt"]
  }
};